// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PP.Treino.API.Data;

namespace PP.Treino.API.Migrations
{
    [DbContext(typeof(TreinoContext))]
    partial class TreinoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PP.Treino.API.Models.Exercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercicio");
                });

            modelBuilder.Entity("PP.Treino.API.Models.ExercicioCarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Carga")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExercicioTreinoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioTreinoId");

                    b.ToTable("ExercicioCarga");
                });

            modelBuilder.Entity("PP.Treino.API.Models.ExercicioTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepeticaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("RepeticaoId");

                    b.HasIndex("TreinoId")
                        .HasName("IDX_Treino");

                    b.ToTable("ExercicioTreino");
                });

            modelBuilder.Entity("PP.Treino.API.Models.Repeticao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Repeticao");
                });

            modelBuilder.Entity("PP.Treino.API.Models.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Treino");
                });

            modelBuilder.Entity("PP.Treino.API.Models.ExercicioCarga", b =>
                {
                    b.HasOne("PP.Treino.API.Models.ExercicioTreino", "ExercicioTreino")
                        .WithMany("ExercicioCarga")
                        .HasForeignKey("ExercicioTreinoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PP.Treino.API.Models.ExercicioTreino", b =>
                {
                    b.HasOne("PP.Treino.API.Models.Exercicio", null)
                        .WithMany("ExercicioTreino")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PP.Treino.API.Models.Repeticao", null)
                        .WithMany("ExercicioTreino")
                        .HasForeignKey("RepeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PP.Treino.API.Models.Treino", null)
                        .WithMany("ExercicioTreino")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
